from easydict import EasyDict as edict
import yaml
import copy
import os

"""
Add default config for OSTrack.
"""
cfg = edict()
cfg.BASE_CONFIG = ""
cfg.EXPERIMENT_NAME = ""
cfg.MODEL_ROLE = "unspecified"
cfg.B0_CHECKPOINT = ""
cfg.TRAIN_PCUM_ONLY = False
cfg.FIXED_FINAL_EPOCH = 0

# MODEL
cfg.MODEL = edict()
cfg.MODEL.PRETRAIN_FILE = "mae_pretrain_vit_base.pth"
cfg.MODEL.EXTRA_MERGER = False
cfg.MODEL.USE_SEARCH_PROMPT = False
cfg.MODEL.PROMPT_HIDDEN_DIM = 32
cfg.MODEL.PROMPT_INIT_SCALE = 0.1

cfg.MODEL.PCUM = edict()
cfg.MODEL.PCUM.ENABLED = False
cfg.MODEL.PCUM.LOCAL_ONLY = True
cfg.MODEL.PCUM.TOKEN_DIM = 192
cfg.MODEL.PCUM.PROMPT_DIM = 192
cfg.MODEL.PCUM.NUM_PROMPTS = 4
cfg.MODEL.PCUM.TOPK = 16
cfg.MODEL.PCUM.SALIENCY_SOURCE = "feature_norm"
cfg.MODEL.PCUM.FUSION = "gated_add"
cfg.MODEL.PCUM.ALIGN_GATE = "cosine"
cfg.MODEL.PCUM.FUSION_INIT_SCALE = 0.1
cfg.MODEL.PCUM.FUSION_SCALE_MAX = 0.0
cfg.MODEL.PCUM.REMOTE_AGGREGATION = "mean"
cfg.MODEL.PCUM.REMOTE_WEIGHT_TEMPERATURE = 0.25
cfg.MODEL.PCUM.REMOTE_WEIGHT_EPS = 1e-6
cfg.MODEL.PCUM.REMOTE_WEIGHT_MIN_QUALITY = 0.0
cfg.MODEL.PCUM.REMOTE_WEIGHT_DIAGNOSTICS = True
cfg.MODEL.PCUM.PROMPT_POOL = "mean"
cfg.MODEL.PCUM.REMOTE_SUPPRESSION_ENABLED = False
cfg.MODEL.PCUM.REMOTE_SUPPRESSION_GATE_INIT_BIAS = -4.0
cfg.MODEL.PCUM.REMOTE_SUPPRESSION_ACTIVE_THRESHOLD = 0.5

# C3R is an independent, default-off collaboration attachment.  The v1 wire
# dimensions and safety constants are frozen by the audited research blueprint.
cfg.MODEL.C3R = edict()
cfg.MODEL.C3R.ENABLED = False
cfg.MODEL.C3R.VARIANT = "c1"
cfg.MODEL.C3R.TOKEN_DIM = 192
cfg.MODEL.C3R.MESSAGE_DIM = 64
cfg.MODEL.C3R.NUM_PROMPTS = 4
cfg.MODEL.C3R.MAX_GATE = 0.25
cfg.MODEL.C3R.PEER_NORM_CAP = 0.25
cfg.MODEL.C3R.AGGREGATE_NORM_CAP = 0.35
cfg.MODEL.C3R.MAX_AGE_INTERVALS = 4
cfg.MODEL.C3R.PACKET_VERSION = 1

# Separate default-off Temporal Gate v2 sidecar. These values are frozen and
# are not architecture, mapping, or optimization search knobs.
cfg.MODEL.TEMPORAL_GATE = edict()
cfg.MODEL.TEMPORAL_GATE.ENABLED = False
cfg.MODEL.TEMPORAL_GATE.INPUT_DIM = 10
cfg.MODEL.TEMPORAL_GATE.HIDDEN_DIM = 16
cfg.MODEL.TEMPORAL_GATE.WINDOW = 8
cfg.MODEL.TEMPORAL_GATE.MAX_GATE = 0.25
cfg.MODEL.TEMPORAL_GATE.GATE_MAPPING = "relu_tanh"

cfg.MODEL.FCVC = edict()
cfg.MODEL.FCVC.ENABLED = False
cfg.MODEL.FCVC.TOKEN_DIM = 192
cfg.MODEL.FCVC.EMBED_DIM = 128
cfg.MODEL.FCVC.NUM_QUERIES = 8
cfg.MODEL.FCVC.NUM_SENDERS = 2
cfg.MODEL.FCVC.NUM_HEADS = 4
cfg.MODEL.FCVC.SAMPLES_PER_SENDER = 4
cfg.MODEL.FCVC.MID_TAP_AFTER_BLOCK = 3
cfg.MODEL.FCVC.HIGH_TAP_AFTER_BLOCK = 6
cfg.MODEL.FCVC.REPLAY_START_BLOCK = 4
cfg.MODEL.FCVC.REPLAY_END_BLOCK = 6

cfg.MODEL.RETURN_INTER = False
cfg.MODEL.RETURN_STAGES = [2, 5, 8, 11]

# MODEL.BACKBONE
cfg.MODEL.BACKBONE = edict()
cfg.MODEL.BACKBONE.TYPE = "vit_base_patch16_224"
cfg.MODEL.BACKBONE.STRIDE = 16
cfg.MODEL.BACKBONE.MID_PE = False
cfg.MODEL.BACKBONE.SEP_SEG = False
cfg.MODEL.BACKBONE.CAT_MODE = 'direct'
cfg.MODEL.BACKBONE.MERGE_LAYER = 0
cfg.MODEL.BACKBONE.ADD_CLS_TOKEN = False
cfg.MODEL.BACKBONE.CLS_TOKEN_USE_MODE = 'ignore'
cfg.MODEL.BACKBONE.PRUNING_ENABLED = False
cfg.MODEL.BACKBONE.DYNAMIC_THRESHOLD_ENABLED = False
cfg.MODEL.BACKBONE.TOKEN_COMPENSATION_ENABLED = False

cfg.MODEL.BACKBONE.CE_LOC = []
cfg.MODEL.BACKBONE.CE_KEEP_RATIO = []
cfg.MODEL.BACKBONE.CE_TEMPLATE_RANGE = 'ALL'  # choose between ALL, CTR_POINT, CTR_REC, GT_BOX

# MODEL.HEAD
cfg.MODEL.HEAD = edict()
cfg.MODEL.HEAD.TYPE = "CENTER"
cfg.MODEL.HEAD.NUM_CHANNELS = 256

# TRAIN
cfg.TRAIN = edict()
cfg.TRAIN.LR = 0.0001
cfg.TRAIN.WEIGHT_DECAY = 0.0001
cfg.TRAIN.EPOCH = 500
cfg.TRAIN.TOTAL_EPOCH = 500
cfg.TRAIN.LR_DROP_EPOCH = 400
cfg.TRAIN.BATCH_SIZE = 16
cfg.TRAIN.NUM_WORKER = 8
cfg.TRAIN.OPTIMIZER = "ADAMW"
cfg.TRAIN.BACKBONE_MULTIPLIER = 0.1
cfg.TRAIN.GIOU_WEIGHT = 2.0
cfg.TRAIN.L1_WEIGHT = 5.0
cfg.TRAIN.FOCAL_WEIGHT = 5.0
cfg.TRAIN.PROMPT_CONSIST_WEIGHT = 5.0
cfg.TRAIN.FREEZE_LAYERS = [0, ]
cfg.TRAIN.PRINT_INTERVAL = 50
cfg.TRAIN.VAL_EPOCH_INTERVAL = 10
cfg.TRAIN.GRAD_CLIP_NORM = 0.1
cfg.TRAIN.AMP = False
cfg.TRAIN.RESUME = False

cfg.TRAIN.CE_START_EPOCH = 20  # candidate elimination start epoch
cfg.TRAIN.CE_WARM_EPOCH = 80  # candidate elimination warm up epoch
cfg.TRAIN.DROP_PATH_RATE = 0.05  # drop path rate for ViT backbone
cfg.TRAIN.FLOPS_START_EPOCH = 0
cfg.TRAIN.FLOPS_END_EPOCH = 0
cfg.TRAIN.INITIAL_FLOPS_TARGET = 10e8
cfg.TRAIN.MAX_FLOPS_TARGET = 7e8
cfg.TRAIN.FLOPS_WEIGHT = 0.0
cfg.TRAIN.PROMPT_DROP_PROB = 0.3
cfg.TRAIN.PROMPT_NOISE_STD = 0.08
cfg.TRAIN.PROMPT_WRONG_PROB = 0.1
cfg.TRAIN.PROMPT_GATE_WEIGHT = 0.01
cfg.TRAIN.PROMPT_ONLY = False
cfg.TRAIN.FREEZE_BACKBONE = False
cfg.TRAIN.FREEZE_HEAD = False
cfg.TRAIN.PARTIAL_ADAPTATION = edict()
cfg.TRAIN.PARTIAL_ADAPTATION.ENABLED = False
cfg.TRAIN.PARTIAL_ADAPTATION.BACKBONE_BLOCKS = []
cfg.TRAIN.PARTIAL_ADAPTATION.TRAIN_FINAL_NORM = False
cfg.TRAIN.PARTIAL_ADAPTATION.TRAIN_HEAD = False
cfg.TRAIN.PARTIAL_ADAPTATION.BACKBONE_LR = 2.4e-6
cfg.TRAIN.PARTIAL_ADAPTATION.HEAD_LR = 8e-6
cfg.TRAIN.PARTIAL_ADAPTATION.FLAT_MULTIVIEW_BASELINE = False
cfg.TRAIN.MULTIVIEW = edict()
# Loader selection is independent from PCUM so a no-PCUM control can consume
# the exact same grouped multi-view samples. Legacy PCUM configs keep their
# previous behavior through TRAIN.PCUM.USE_REAL_MULTIVIEW in train_script.py.
cfg.TRAIN.MULTIVIEW.ENABLED = False
cfg.TRAIN.MULTIVIEW.FLAT_BASELINE = False
cfg.TRAIN.MULTIVIEW.REQUIRE_ALL_VIEWS_VISIBLE = False
cfg.TRAIN.MULTIVIEW.CANONICAL_VIEW_ORDER = False
cfg.TRAIN.MULTIVIEW.INDEPENDENT_VIEW_SAMPLING = False
cfg.TRAIN.MULTIVIEW.DIAGNOSTICS_ENABLED = False
cfg.TRAIN.MULTIVIEW.SAVE_VAL_MANIFEST = False
cfg.TRAIN.PCUM_RANKING = edict()
cfg.TRAIN.PCUM_RANKING.ENABLED = False
cfg.TRAIN.PCUM_RANKING.FREEZE_BACKBONE = False
cfg.TRAIN.PCUM_RANKING.FREEZE_HEAD = False
cfg.TRAIN.PCUM_RANKING.LAMBDA_DELAY = 0.1
cfg.TRAIN.PCUM_RANKING.VISIBLE_ONLY = False
cfg.TRAIN.PCUM_RANKING.MARGIN_ZERO = 0.02
cfg.TRAIN.PCUM_RANKING.MARGIN_LOCAL = 0.0
cfg.TRAIN.PCUM_RANKING.SAFE_MARGIN = 0.0
cfg.TRAIN.PCUM_RANKING.LAMBDA_ZERO = 0.1
cfg.TRAIN.PCUM_RANKING.LAMBDA_LOCAL = 0.05
cfg.TRAIN.PCUM_RANKING.LAMBDA_SAFE = 0.0
cfg.TRAIN.PCUM_RANKING.REMOTE_SUPPRESSION_ONLY = False
cfg.TRAIN.PCUM_RANKING.LAMBDA_SUPPRESS_BCE = 0.10
cfg.TRAIN.PCUM_RANKING.LAMBDA_SUPPRESS_MEAN = 0.001
cfg.TRAIN.PCUM_RANKING.SUPPRESS_LABEL_MARGIN = 0.0
cfg.TRAIN.PCUM_CONSIST_WEIGHT = 0.0
cfg.TRAIN.PCUM_LR = 8e-6
cfg.TRAIN.MAX_ITERS_PER_EPOCH = 0
cfg.TRAIN.SEED = 0
cfg.TRAIN.PCUM = edict()
cfg.TRAIN.PCUM.ALIGN_LOSS_WEIGHT = 0.0
cfg.TRAIN.PCUM.USE_PSEUDO_REMOTE = True
cfg.TRAIN.PCUM.STOP_GRAD_TEACHER = True
cfg.TRAIN.PCUM.USE_REAL_MULTIVIEW = False
cfg.TRAIN.PCUM.DETACH_REAL_REMOTE = True
cfg.TRAIN.PCUM.REAL_MULTIVIEW_LOSS_MODE = "all_views"
cfg.TRAIN.PCUM.REQUIRE_ALL_VIEWS_VISIBLE = False
cfg.TRAIN.PCUM.USE_REMOTE_VISIBLE_MASK = False
cfg.TRAIN.PCUM.CANONICAL_VIEW_ORDER = False
cfg.TRAIN.PCUM.REAL_MULTIVIEW_LOSS_WEIGHTS = []
cfg.TRAIN.PCUM.REMOTE_DROPOUT_PROB = 0.0
cfg.TRAIN.PCUM.PAIRED_SUPERVISION = False
cfg.TRAIN.PCUM.LOCAL_LOSS_WEIGHT = 1.0
cfg.TRAIN.PCUM.COLLAB_LOSS_WEIGHT = 1.0
cfg.TRAIN.FCVC = edict()
cfg.TRAIN.FCVC.ENABLED = False
cfg.TRAIN.FCVC.STUDENT_LR = 1.0e-4
cfg.TRAIN.FCVC.TEACHER_LR = 5.0e-5
cfg.TRAIN.FCVC.WEIGHT_DECAY = 1.0e-4
cfg.TRAIN.FCVC.SEED = 42
cfg.TRAIN.PCUM.SAFE_LOSS_WEIGHT = 0.0
cfg.TRAIN.PCUM.SAFE_MARGIN = 0.0
cfg.TRAIN.PCUM.SAFE_HARD_SAMPLE_QUANTILE = 0.0
cfg.TRAIN.PCUM.RANKING_ENABLED = False
cfg.TRAIN.PCUM.RANK_ZERO_MARGIN = 0.02
cfg.TRAIN.PCUM.RANK_DELAY_MARGIN = 0.02
cfg.TRAIN.PCUM.RANK_LOCAL_MARGIN = 0.0
cfg.TRAIN.PCUM.RANK_ZERO_WEIGHT = 0.1
cfg.TRAIN.PCUM.RANK_DELAY_WEIGHT = 0.1
cfg.TRAIN.PCUM.RANK_LOCAL_WEIGHT = 0.05
cfg.TRAIN.PCUM.DELAY_BRANCH_MODE = "batch_roll"
cfg.TRAIN.PCUM.DIAGNOSTICS_ENABLED = False
cfg.TRAIN.PCUM.DIAGNOSTICS_INTERVAL = 50

cfg.TRAIN.C3R = edict()
cfg.TRAIN.C3R.ENABLED = False
cfg.TRAIN.C3R.FREEZE_LOCAL = True
cfg.TRAIN.C3R.LR = 0.0001
cfg.TRAIN.C3R.GATE_RANK_WEIGHT = 0.10
cfg.TRAIN.C3R.RESIDUAL_BUDGET_WEIGHT = 0.05
cfg.TRAIN.C3R.SEED = 20260716
cfg.TRAIN.C3R.REMOTE_DROPOUT_PROB = 0.25
cfg.TRAIN.C3R.DELAYS = [0, 1, 2, 4]
cfg.TRAIN.C3R.DELAY_PROBS = [0.50, 0.20, 0.20, 0.10]
cfg.TRAIN.C3R.SEMANTIC_CORRUPTION_PROB = 0.15
cfg.TRAIN.C3R.WRONG_REMOTE_PROB = 0.20
cfg.TRAIN.C3R.ONE_GOOD_ONE_BAD_PROB = 0.15
cfg.TRAIN.C3R.PERTURBATIONS_ENABLED = False

cfg.TRAIN.TEMPORAL_GATE = edict()
cfg.TRAIN.TEMPORAL_GATE.ENABLED = False
cfg.TRAIN.TEMPORAL_GATE.SEED = 20260718
cfg.TRAIN.TEMPORAL_GATE.LR = 0.001
cfg.TRAIN.TEMPORAL_GATE.WEIGHT_DECAY = 0.0001
cfg.TRAIN.TEMPORAL_GATE.BATCH_SIZE = 256
cfg.TRAIN.TEMPORAL_GATE.MAX_EPOCHS = 20
cfg.TRAIN.TEMPORAL_GATE.GRAD_CLIP_NORM = 1.0
cfg.TRAIN.TEMPORAL_GATE.EARLY_STOP_PATIENCE = 3
cfg.TRAIN.TEMPORAL_GATE.TARGET = "delta_diou"
cfg.TRAIN.TEMPORAL_GATE.LOSS = "smooth_l1"
cfg.TRAIN.TEMPORAL_GATE.SMOOTH_L1_BETA = 1.0

# TRAIN.SCHEDULER
cfg.TRAIN.SCHEDULER = edict()
cfg.TRAIN.SCHEDULER.TYPE = "step"
cfg.TRAIN.SCHEDULER.DECAY_RATE = 0.1
cfg.TRAIN.SCHEDULER.MILESTONES = [40, 60]
cfg.TRAIN.SCHEDULER.GAMMA = 0.1

# DATA
cfg.DATA = edict()
cfg.DATA.SAMPLER_MODE = "causal"  # sampling methods
cfg.DATA.MEAN = [0.485, 0.456, 0.406]
cfg.DATA.STD = [0.229, 0.224, 0.225]
cfg.DATA.MAX_SAMPLE_INTERVAL = 200
# DATA.TRAIN
cfg.DATA.TRAIN = edict()
# cfg.DATA.TRAIN.DATASETS_NAME = ["LASOT", "GOT10K_vottrain"]
cfg.DATA.TRAIN.DATASETS_NAME = ["LASOT"]
# cfg.DATA.TRAIN.DATASETS_RATIO = [1, 1]
cfg.DATA.TRAIN.DATASETS_RATIO = [1]
cfg.DATA.TRAIN.SAMPLE_PER_EPOCH = 60000
cfg.DATA.TRAIN.SPLIT_FILE = ""
# DATA.VAL
cfg.DATA.VAL = edict()
cfg.DATA.VAL.DATASETS_NAME = ["LASOT_VAL"]
cfg.DATA.VAL.DATASETS_RATIO = [1]
cfg.DATA.VAL.SAMPLE_PER_EPOCH = 10000
cfg.DATA.VAL.SPLIT_FILE = ""
# DATA.SEARCH
cfg.DATA.SEARCH = edict()
cfg.DATA.SEARCH.SIZE = 320
cfg.DATA.SEARCH.FACTOR = 5.0
cfg.DATA.SEARCH.CENTER_JITTER = 3
cfg.DATA.SEARCH.SCALE_JITTER = 0.25
cfg.DATA.SEARCH.NUMBER = 1
# DATA.TEMPLATE
cfg.DATA.TEMPLATE = edict()
cfg.DATA.TEMPLATE.NUMBER = 1
cfg.DATA.TEMPLATE.SIZE = 128
cfg.DATA.TEMPLATE.FACTOR = 2.0
cfg.DATA.TEMPLATE.CENTER_JITTER = 0
cfg.DATA.TEMPLATE.SCALE_JITTER = 0

# TEST
cfg.TEST = edict()
cfg.TEST.TEMPLATE_FACTOR = 2.0
cfg.TEST.TEMPLATE_SIZE = 128
cfg.TEST.SEARCH_FACTOR = 5.0
cfg.TEST.SEARCH_SIZE = 320
cfg.TEST.EPOCH = 500
cfg.TEST.SAVE_DIR = ""
cfg.TEST.CHECKPOINT_NAME = ""
cfg.TEST.USE_SEARCH_PROMPT = False
cfg.TEST.PROMPT_SELF_SCORE_THR = 0.25
cfg.TEST.PROMPT_SELF_APCE_THR = 100.0
cfg.TEST.PROMPT_PEER_SCORE_THR = 0.35
cfg.TEST.PROMPT_PEER_APCE_THR = 120.0
cfg.TEST.PROMPT_LARGE_SEARCH_FACTOR = 6.0
cfg.TEST.PCUM = edict()
cfg.TEST.PCUM.USE_REMOTE = False
cfg.TEST.PCUM.REMOTE_ABLATION = "normal"
cfg.TEST.PCUM.REMOTE_ABLATION_OFFSET = 10
cfg.TEST.PCUM.REMOTE_STATE_SOURCE = "tracker"
cfg.TEST.PCUM.REMOTE_SCORE_THR = 0.0
cfg.TEST.PCUM.REMOTE_APCE_THR = 0.0
cfg.TEST.PCUM.MIN_REMOTE_PROMPTS = 1
cfg.TEST.PCUM.USE_REMOTE_ONLY_WHEN_LOCAL_LOW = False
cfg.TEST.PCUM.USE_REMOTE_VISIBLE_MASK = False
cfg.TEST.PCUM.LOCAL_LOW_SCORE_THR = 0.25
cfg.TEST.PCUM.LOCAL_LOW_APCE_THR = 100.0
cfg.TEST.PCUM.LOCAL_LOW_MODE = "or"
cfg.TEST.PCUM.KEEP_LOCAL_IF_REMOTE_WORSE = True
cfg.TEST.PCUM.REMOTE_SCORE_MAX_DROP = 0.05
cfg.TEST.PCUM.KEEP_LOCAL_IF_REMOTE_CONFIDENCE_WORSE = False
cfg.TEST.PCUM.REMOTE_CONFIDENCE_MAX_DROP = 0.02
cfg.TEST.PCUM.SAVE_DECISION_LOG = False
cfg.TEST.PCUM.RELIABILITY_SELECTOR = "none"
cfg.TEST.PCUM.SELECTOR_MARGIN = 0.0
cfg.TEST.PCUM.SELECTOR_MOTION_THRESHOLD = 0.0
cfg.TEST.PCUM.SELECTOR_DIAGNOSTICS = True
cfg.TEST.PCUM.USE_MOTION_REDETECT = False
cfg.TEST.PCUM.MOTION_REDETECT_SEARCH_FACTOR = 6.0
cfg.TEST.PCUM.MOTION_REDETECT_MIN_REMOTE = 1
cfg.TEST.PCUM.MOTION_REDETECT_MIN_RELIABILITY = 0.25
cfg.TEST.PCUM.MOTION_REDETECT_MAX_NORM_MOTION = 2.0
cfg.TEST.PCUM.MOTION_REDETECT_APCE_NORM = 200.0
cfg.TEST.PCUM.MOTION_REDETECT_USE_LOCAL_CANDIDATE = True
cfg.TEST.PCUM.MOTION_REDETECT_LOCAL_MIN_GAIN = 0.0
cfg.TEST.PCUM.USE_MOTION_CONFIDENCE = False
cfg.TEST.PCUM.FRAME_DIAGNOSTICS = edict()
cfg.TEST.PCUM.FRAME_DIAGNOSTICS.ENABLED = False
cfg.TEST.PCUM.FRAME_DIAGNOSTICS.LABEL = ""
cfg.TEST.PCUM.FRAME_DIAGNOSTICS.NEUTRAL_EPS = 0.01
cfg.TEST.MOTION_STATE = edict()
cfg.TEST.MOTION_STATE.ENABLED = False
cfg.TEST.MOTION_STATE.SHADOW_ONLY = True
cfg.TEST.MOTION_STATE.LOG_ENABLED = False
cfg.TEST.MOTION_STATE.VELOCITY_EMA = 0.8
cfg.TEST.MOTION_STATE.MAX_HISTORY = 10
cfg.TEST.MOTION_STATE.SCORE_LOW = 0.0
cfg.TEST.MOTION_STATE.SCORE_RECOVER = 0.0
cfg.TEST.MOTION_STATE.APCE_LOW = 0.0
cfg.TEST.MOTION_STATE.APCE_RECOVER = 0.0
cfg.TEST.MOTION_STATE.MOTION_RESIDUAL_HIGH = 0.0
cfg.TEST.MOTION_STATE.BORDER_MARGIN = 0.1
cfg.TEST.MOTION_STATE.K_LOST = 3
cfg.TEST.MOTION_STATE.K_NORMAL = 2
cfg.TEST.MOTION_STATE.K_RECOVER = 3
cfg.TEST.MCR = edict()
cfg.TEST.MCR.ENABLED = False
cfg.TEST.MCR.SHADOW_ONLY = True
cfg.TEST.MCR.MOTION_ENABLED = True
cfg.TEST.MCR.LOCAL_ENABLED = True
cfg.TEST.MCR.GLOBAL_ENABLED = False
cfg.TEST.MCR.REMOTE_VERIFY_ENABLED = True
cfg.TEST.MCR.MULTIFRAME_CONFIRM_ENABLED = True
cfg.TEST.MCR.VERIFY_EVERY_FRAME_WHEN_PENDING = True
cfg.TEST.MCR.LOCAL_INTERVAL = 10
cfg.TEST.MCR.LOCAL_SCALES = [1.5, 2.0, 3.0]
cfg.TEST.MCR.ANCHORS = ["current", "motion", "last_reliable"]
cfg.TEST.MCR.MAX_REGIONS_PER_TRIGGER = 6
cfg.TEST.MCR.ANCHOR_DEDUP_NORMALIZED_DISTANCE = 0.25
cfg.TEST.MCR.VELOCITY_EMA = 0.8
cfg.TEST.MCR.MAX_HISTORY = 10
cfg.TEST.MCR.CONFIRM_FRAMES = 2
cfg.TEST.MCR.VERIFY_WINDOW = 3
cfg.TEST.MCR.VERIFY_SEARCH_SCALE = 1.5
cfg.TEST.MCR.MIN_CONFIRM_IOU = 0.30
cfg.TEST.MCR.MAX_CONFIRM_CENTER_DISTANCE = 1.0
cfg.TEST.MCR.COOLDOWN_AFTER_SWITCH = 5
cfg.TEST.MCR.UPDATE_FREEZE_FRAMES_AFTER_SWITCH = 3
cfg.TEST.MCR.VISUAL_WEIGHT = 0.55
cfg.TEST.MCR.REMOTE_WEIGHT = 0.20
cfg.TEST.MCR.MOTION_WEIGHT = 0.15
cfg.TEST.MCR.GEOMETRY_WEIGHT = 0.10
cfg.TEST.MCR.MOTION_DISTANCE_SCALE = 2.0
cfg.TEST.MCR.MIN_VISUAL_SCORE = 0.30
cfg.TEST.MCR.MIN_CANDIDATE_SCORE = 0.50
cfg.TEST.MCR.SWITCH_MARGIN = 0.05
cfg.TEST.MCR.MAX_AREA_RATIO_CHANGE = 4.0
cfg.TEST.MCR.MAX_ASPECT_RATIO_CHANGE = 3.0
cfg.TEST.MCR.CURRENT_LARGE_SCALE_GEOMETRY_GUARD = edict()
cfg.TEST.MCR.CURRENT_LARGE_SCALE_GEOMETRY_GUARD.ENABLED = False
cfg.TEST.MCR.CURRENT_LARGE_SCALE_GEOMETRY_GUARD.MIN_SCALE = 2.0
cfg.TEST.MCR.CURRENT_LARGE_SCALE_GEOMETRY_GUARD.MIN_GEOMETRY = 0.4
cfg.TEST.MCR.RELIABLE_SCORE_THRESHOLD = 0.30
cfg.TEST.MCR.RELIABLE_APCE_THRESHOLD = 0.0
cfg.TEST.MCR.GLOBAL_INTERVAL = 60
cfg.TEST.MCR.GLOBAL_GRID = [3, 3]
cfg.TEST.MCR.GLOBAL_TOPK = 3
cfg.TEST.COOP = edict()
cfg.TEST.COOP.ENABLED = False
cfg.TEST.COOP.FUSION = "none"
cfg.TEST.COOP.PAYLOAD = "bbox_score"
cfg.TEST.COOP.SEND_INTERVAL = 1
cfg.TEST.COOP.BANDWIDTH_LIMIT_BYTES_PER_FRAME = None
cfg.TEST.COOP.PACKET_LOSS = 0.0
cfg.TEST.COOP.DELAY_FRAMES = 0
cfg.TEST.COOP.MAX_NEIGHBORS = None
cfg.TEST.COOP.SEED = 0
cfg.TEST.COOP.SAVE_STATS = True
cfg.TEST.C3R = edict()
cfg.TEST.C3R.ENABLED = False
cfg.TEST.C3R.RECEIVER_ID = 0
cfg.TEST.C3R.FRAME_INTERVAL_MS = 33
cfg.TEST.C3R.COMMUNICATION_STRIDE = 1
cfg.TEST.C3R.ACCOUNTING_ENABLED = True
cfg.TEST.C3R.DIAGNOSTICS_ENABLED = False
cfg.TEST.TEMPORAL_GATE = edict()
cfg.TEST.TEMPORAL_GATE.ENABLED = False
cfg.TEST.TEMPORAL_GATE.CHECKPOINT = ""
cfg.TEST.TEMPORAL_GATE.CHECKPOINT_SHA256 = ""
cfg.TEST.TEMPORAL_GATE.ROLLOUT_CAPTURE = False
cfg.TEST.TEMPORAL_GATE.COUNTERFACTUAL_DIAGNOSTICS = False

_DEFAULT_CFG = copy.deepcopy(cfg)


def get_default_config():
    """Return an isolated config so audit tools do not mutate global state."""
    return copy.deepcopy(_DEFAULT_CFG)


def _edict2dict(dest_dict, src_edict):
    if isinstance(dest_dict, dict) and isinstance(src_edict, dict):
        for k, v in src_edict.items():
            if not isinstance(v, edict):
                dest_dict[k] = v
            else:
                dest_dict[k] = {}
                _edict2dict(dest_dict[k], v)
    else:
        return


def gen_config(config_file):
    cfg_dict = {}
    _edict2dict(cfg_dict, cfg)
    with open(config_file, 'w') as f:
        yaml.dump(cfg_dict, f, default_flow_style=False)


def _update_config(base_cfg, exp_cfg):
    if isinstance(base_cfg, dict) and isinstance(exp_cfg, edict):
        for k, v in exp_cfg.items():
            if k in base_cfg:
                if not isinstance(v, dict):
                    base_cfg[k] = v
                else:
                    _update_config(base_cfg[k], v)
            else:
                raise ValueError("{} not exist in config.py".format(k))
    else:
        return


def update_config_from_file(filename, base_cfg=None):
    exp_config = None
    filename = str(filename)
    with open(filename) as f:
        exp_config = edict(yaml.safe_load(f))
        base_config_name = exp_config.get("BASE_CONFIG", "")
        target_cfg = base_cfg if base_cfg is not None else cfg
        if base_cfg is None:
            cfg.clear()
            cfg.update(copy.deepcopy(_DEFAULT_CFG))
        if base_config_name:
            base_path = base_config_name
            if not str(base_path).endswith(".yaml"):
                base_path = str(base_path) + ".yaml"
            if not os.path.isabs(base_path):
                base_path = os.path.join(os.path.dirname(filename), base_path)
            if os.path.abspath(base_path) == os.path.abspath(filename):
                raise ValueError("BASE_CONFIG cannot point to itself: {}".format(filename))
            update_config_from_file(base_path, base_cfg=target_cfg)
        if base_cfg is not None:
            _update_config(base_cfg, exp_config)
        else:
            _update_config(cfg, exp_config)
